apiVersion: v1
kind: Secret
metadata:
  name: appnotes-secret
  namespace: app-note
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://app_user:arSMol35ulYNMqCs@cluster0.akd0umq.mongodb.net/?appName=Cluster0"
  
